import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import useIgnobleApi from "../hooks/useIgnobleApi";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [selectedYear, setSelectedYear] = useState(null);

  const { prizes, years } = useIgnobleApi(selectedYear);

  console.log("PRIZES", prizes, "YEARS", years);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {years.sort().map((year) => (
            <button
              key={year}
              style={{
                backgroundColor:
                  selectedYear === year ? "dodgerblue" : "initial",
              }}
              onClick={() => setSelectedYear(year)}
            >
              {year}
            </button>
          ))}
        </div>
        <div>
          <h2>{selectedYear}</h2>
          {prizes.map((prize) => {
            return (
              <details key={prize.id}>
                <summary>{prize.category}</summary>
                <p>{prize.rationale}</p>
              </details>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
